services:
  personal-website:
    container_name: personal-website
    image: harrisonfry/personal-website
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}

networks:
  default:
    name: website-network
